site_name: Отчет к лабораторным работам по курсу "WEB-пограммирование"
nav:
 - Краткая информация о лабораторных работах: index.md
 - Лабораторная работа №1:
   - Задание 1: LR_1/task1.md
   - Задание 2: LR_1/task2.md
   - Задание 3: LR_1/task3.md
   - Задание 4: LR_1/task4.md
   - Задание 5: LR_1/task5.md
 - Практическая работа №2:
   - Задание 1: PR_2/task1.md
   - Задание 2: PR_2/task2.md
   - Задание 3: PR_2/task3.md
 - Лабораторная работа №2:
   - Задание: LR_2/task.md
 - Практическая работа №3:
   - Задание 1: PR_3/task1.md
   - Задание 2: PR_3/task2.md
   - Задание 3: PR_3/task2.md
theme:
 name: dracula